name: check on PR
on:
  - pull_request
  - workflow_dispatch

jobs:
  check-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install packages
        run: npm ci
      - name: prettier
        run: npm run lint
